name: Build LaTeX document
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_use_xelatex: true
          root_file: Ufuk-Kayserilioglu-Resume.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Ufuk-Kayserilioglu-Resume.pdf
          path: Ufuk-Kayserilioglu-Resume.pdf
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
      - name: Upload artifacts to AWS S3
        uses: usualdesigner/s3-artifact-upload@main
        with:
          bucket-name: "ufuk-kayserilioglu-resume"
          file: Ufuk-Kayserilioglu-Resume.pdf
